spring.application.name=02_myBatis

# server port
server.port=8282

# ViewResolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# mapper 파일 경로 지정 (resources/mappers 하위의 모든 xml)
# classpath:는 src/main/resources/까지가 기본 경로라고 보면 됨
# *: 현재 디렉토리 안에서만 찾기 / **: 현재 디렉토리랑 그 아래 모든 하위 폴더들까지 다 찾기
mybatis.mapper-locations=classpath:mappers/**/*.xml

# Type Alias 패키지 경로 지정 (XML에서 클래스명만 사용할 수 있게 설정)
# xml에서 패키지 경로 없이 클래스명만 입력할 수 있게 별칭 등록
mybatis.type-aliases-package=com.kh.mybatis.model.dto

# mybatis setting
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=C##JDBC
spring.datasource.password=JDBC